spring:
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: 1
        spring:
          json:
            add:
              type:
                headers: false
  thymeleaf:
    cache: false
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/task_manager_db
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    #      update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

topic: test